[default]
exclude = [
    "uv.lock",
    "lzyank.toml",
    ".github",
    "*.ini",
    ".pre-commit-config.yaml",
    "LICENSE",
    "codecov.yaml",
    "mkdocs.yml",
    "tests/data"
]

[actions]
include = [".github/"]
