site_name: BioMCP
repo_url: https://github.com/genomoncology/biomcp
site_url: https://biomcp.org/
site_description: Biomedical Model Context Protocol Server
site_author: Ian Maurer
edit_uri: edit/main/docs/
repo_name: genomoncology/biomcp
copyright: Maintained by <a href="https://genomoncology.com">genomoncology</a>.

nav:
  - Home: index.md
  - Getting Started:
      - Quickstart CLI: getting-started/01-quickstart-cli.md
      - Claude Desktop Integration: getting-started/02-claude-desktop-integration.md
      - Authentication and API Keys: getting-started/03-authentication-and-api-keys.md
  - Concepts:
      - What is BioMCP?: concepts/01-what-is-biomcp.md
      - The Deep Researcher Persona: concepts/02-the-deep-researcher-persona.md
      - Sequential Thinking with the Think Tool: concepts/03-sequential-thinking-with-the-think-tool.md
  - User Guides:
      - Command Line Interface: user-guides/01-command-line-interface.md
      - MCP Tools Reference: user-guides/02-mcp-tools-reference.md
      - Integrating with IDEs and Clients: user-guides/03-integrating-with-ides-and-clients.md
  - How-to Guides:
      - Find Articles and cBioPortal Data: how-to-guides/01-find-articles-and-cbioportal-data.md
      - Find Trials with NCI and BioThings: how-to-guides/02-find-trials-with-nci-and-biothings.md
      - Get Comprehensive Variant Annotations: how-to-guides/03-get-comprehensive-variant-annotations.md
      - Predict Variant Effects with AlphaGenome: how-to-guides/04-predict-variant-effects-with-alphagenome.md
      - Logging and Monitoring with BigQuery: how-to-guides/05-logging-and-monitoring-with-bigquery.md
      - Search NCI Organizations and Interventions: how-to-guides/06-search-nci-organizations-and-interventions.md
  - Backend Services Reference:
      - Overview: backend-services-reference/01-overview.md
      - BioThings Suite: backend-services-reference/02-biothings-suite.md
      - cBioPortal: backend-services-reference/03-cbioportal.md
      - ClinicalTrials.gov: backend-services-reference/04-clinicaltrials-gov.md
      - NCI CTS API: backend-services-reference/05-nci-cts-api.md
      - PubTator3: backend-services-reference/06-pubtator3.md
      - AlphaGenome: backend-services-reference/07-alphagenome.md
  - Developer Guides:
      - Server Deployment: developer-guides/01-server-deployment.md
      - Contributing and Testing: developer-guides/02-contributing-and-testing.md
      - Third-Party Endpoints: developer-guides/03-third-party-endpoints.md
  - Blog:
      - AI Assisted Clinical Trial Search: blog/ai-assisted-clinical-trial-search-analysis.md
      - Deep Researcher Persona: blog/researcher-persona-resource.md
  - Reference:
      - Transport Protocol: transport-protocol.md
      - Error Handling: error-handling.md
      - HTTP Client Guide: http-client-guide.md
      - Integration Testing: integration-testing.md
      - Migration Examples: migration-examples.md
      - Performance Optimizations: performance-optimizations.md
  - Examples and Prompts:
      - BioThings Query Examples: tutorials/biothings-prompts.md
      - NCI Search Examples: tutorials/nci-prompts.md
      - Claude Code Integration: tutorials/claude-code-biomcp-alphagenome.md
  - About:
      - GenomOncology: genomoncology.md
      - Changelog: changelog.md
      - Troubleshooting: troubleshooting.md
      - Policies: policies.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/biomcp"]
theme:
  name: material
  # custom_dir: overrides
  favicon: assets/favicon.ico
  logo: assets/icon.png
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/genomoncology/biomcp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/biomcp-python

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  # Consider adding other useful extensions:
  - admonition # Nice looking note/warning boxes
  - pymdownx.details # Collapsible sections
  - pymdownx.highlight: # Code highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets # Include content from other files
  - pymdownx.superfences # Nested code blocks/diagrams
  - pymdownx.tabbed: # Tabbed content
      alternate_style: true
