name = "biomcp-worker"
main = "src/biomcp/workers/worker_entry_stytch.js"
compatibility_date = "2025-04-28"

[vars]
# Environment variables for the worker
# These can be overridden in several ways:
# 1. In the Cloudflare dashboard under Workers & Pages > your-worker > Settings > Variables
# 2. Using wrangler CLI: wrangler secret put REMOTE_MCP_SERVER_URL
# 3. During local development: wrangler dev --var REMOTE_MCP_SERVER_URL="http://localhost:8000"
# 4. In your CI/CD pipeline using environment variables with the format CF_REMOTE_MCP_SERVER_URL
REMOTE_MCP_SERVER_URL = "https://biomcp-remote.genomoncology.io"  # Default value
DEBUG = true

# Security configuration for MCP Streamable HTTP spec compliance
# List of allowed origins for CORS (comma-separated)
ALLOWED_ORIGINS = "https://claude.ai,https://*.claude.ai,http://localhost:*,http://127.0.0.1:*,chrome-extension://*,capacitor://localhost"
# Set to "true" to disable origin validation (NOT recommended for production)
DISABLE_ORIGIN_VALIDATION = false

# Stytch variables
STYTCH_PROJECT_ID      = "project-live-9364e92f-ac08-47d5-9a46-d0fb9443b6f8"
STYTCH_SECRET          = "secret-live-PVH66RKo4S9tlRuiNIb9HGMlpxg2rbxaIRQ="
STYTCH_PUBLIC_TOKEN    = "public-token-live-0cddb5f4-9f30-4acd-8f63-6f712cfd0436"
STYTCH_API_URL = "https://api.stytch.com/v1"
STYTCH_OAUTH_URL = "https://api.stytch.com/v1/public/oauth/google/start"
JWT_SECRET = "cUsCZRZQcVELr26zAHfUJd"

# Sensitive variables should be stored in the Cloudflare dashboard under Workers & Pages > your-worker > Settings > Secrets
# OR you can declare them using npx wrangler secret put BQ_SA_KEY_JSON
# Potential secrets:
# BQ_SA_KEY_JSON
# STYTCH_SECRET


# BigQuery variables
# For production, set these as secrets or environment variables:
# wrangler secret put BQ_PROJECT_ID
# wrangler secret put BQ_DATASET
# wrangler secret put BQ_SA_KEY_JSON
BQ_PROJECT_ID="genomoncology-mcp-7760928578"
BQ_DATASET="biomcp_worker_logs"
BQ_TABLE="worker_logs"

# Sensitive variables should be stored in the Cloudflare dashboard under Workers & Pages > your-worker > Settings > Secrets
# OR you can declare them using npx wrangler secret put BQ_SA_KEY_JSON
# Potential secrets:
# BQ_SA_KEY_JSON
# STYTCH_SECRET


# Note: The ability to allow plaintext connections is now configured in the Cloudflare dashboard
# under Security settings for your Worker

[build]
command = ""

[triggers]
crons = []

[observability.logs]
enabled = true

# KV namespace for storing OAuth tokens and state
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "acfa0cf90ec747c295024058963cca75"
